title: Faisal Ahmed Pasha Mohammed
# Name of your site (displayed in the header)
name: Faisal Ahmed Pasha Mohammed
# Short bio or description (displayed in the header)
description: Passionate about Java, Linux, RDBMS, TCP/IP, Mathematics
footer-links:
  github: faimoh
  linkedin:
sections:
  brief_bio :
    enabled : true
    image :
      enabled : false
      url : false
    content :
      enabled : true
    social_links :
      enabled : true
    github_projects :
      enabled : true
exclude:
  - README.md
