title: Faisal Ahmed Pasha Mohammed
# Name of your site (displayed in the header)
name: Faisal Ahmed Pasha Mohammed
# Short bio or description (displayed in the header)
description: Passionate about Java, Linux, RDBMS, TCP/IP, Mathematics
logo: '/assets/logo.png'
footer-links:
  github: faahpamo
  linkedin:
exclude:
  - README.md
